### ISSUE TITLE
Perhaps iterate over grapheme clusters instead of Unicode scalars

### ISSUE THREAD

**Issue by mgeisler** [mgeisler/textwrap#117]
We currently wrap strings by iterating over Unicode code points (`char` elements) and splitting on whitespace.

The [unicode-segmentation](https://crates.io/crates/unicode-segmentation) crate allows iterating over _grapheme clusters_ instead, which (as far as I understand), means that it will treat things like `"e\u{301}"` (`"e"` followed by a combining accent aigu, e.g. `é`) as a single entity.

When iterating over Unicode strings, it's generally recommended to use grapheme clusters instead of individual code points.

**Comment by mgeisler** [comment]
Simple testing shows that the unicode-width crate treats a combining accent aigu as a character with zero width:
```
    let composed = "é";
    let decomposed = "e\u{301}";
    println!("composed:   {}, len: {}, width: {}",
             composed,
             composed.len(),
             composed.width());
    println!("decomposed: {}, len: {}, width: {}",
             decomposed,
             decomposed.len(),
             decomposed.width());
```
yields
```
composed:   é, len: 2, width: 1
decomposed: é, len: 3, width: 1
```

**Comment by mgeisler** [comment]
Based on that, i suppose our width computations are sound. We only use the iteration to identify `' '` and `'-'` characters, so I guess we're actually good without using the grapheme cluster machinery.

I'll close this ticket for now and then we can reopen later if someone finds an issue with the current implementation.

**Comment by davidkna** [comment]
This does not work with ZWJ-joined emoji like for example: `'👩‍👩‍👦‍👦'.width()` is 8.
