### ISSUE TITLE
Handle ANSI color codes

### ISSUE THREAD

**Issue by mgeisler** [mgeisler/textwrap#140]
Textwrap currently doesn't know about ANSI color codes for colored terminal output. It simply treats these escape codes as any other character and this can mess up the output as shown here: kbknapp/clap-rs#1246.

The custom width functionality of #128 could perhaps be used to solve this problem, but I feel it would be nice if this was a builtin feature (perhaps an optional feature depending on how invasive it will be to handle this).

**Comment by laanwj** [comment]
Yes! this would be very useful for me too, though in my case the codes are not *ANSI* color codes but other game-specific formatting.

A general way to mark parts of the input text as color/formatting would be nice.

Such spans would be ignored for purposes of width estimation, formatting and breaking, but would be emitted in the output in the same place as they were in the input.

**Comment by laanwj** [comment]
Oh wow, hadn't thought of that: as long as the textwrap doesn't change the text, it doesn't have to know about the formatting at all, the string is divided in the same places!

It's unfortunate that this doesn't extend to hyphen-ization or multiple spaces—I guess even that could be fixed up after the fact with a reconciliation pass—though a solution that works on tokens, as you say, would be more elegant.

**Comment by mgeisler** [comment]
I hadn't though of it before you gave me the idea :-D I think you could take the above idea pretty far, but it'll be much nicer if there was some builtin support. I'll see what I can come up with...

**Comment by medusacle** [comment]
might be useful to take inspiration from how cursive handles this for their TextViews, as it more or less exactly implements the above;

they have a `StyledString = SpannedString<Style>` which consists of spans: https://github.com/gyscos/Cursive/blob/master/src/utils/markup/mod.rs#L20, these are parametrized on the struct to be used as style, cursive itself uses https://github.com/gyscos/Cursive/blob/master/src/theme/style.rs#L8
e.g.
```rust
    let mut styled = StyledString::plain("Isn't ");
    styled.append(StyledString::styled("that ", Color::Dark(BaseColor::Red)));
    styled.append(StyledString::styled(
        "cool?",
        Style::from(Color::Light(BaseColor::Blue)).combine(Effect::Bold),
    ));
```
then their word wrapper  which operates on them is here: https://github.com/gyscos/Cursive/blob/master/src/utils/lines/spans/lines_iterator.rs#L13

**Comment by pksunkara** [comment]
@mgeisler Any update on this? Would like to get it fixed on clap.

**Comment by mgeisler** [comment]
Hi @pksunkara, thanks for reminding me. I haven't looked more into this since I wrote the Markdown example above. However, I took a look now and found that it was relatively easy to add support for this, please see https://github.com/mgeisler/textwrap/pull/179.
