### ISSUE TITLE
Release of version with hyphenation 0.7

### ISSUE THREAD

**Issue by silwol** [mgeisler/textwrap#151]
In Debian, we packaged textwrap 0.10. We usually try to package the latest versions of crates only, and for the packages to migrate from the unstable to the testing repository, all feature dependencies need to be packaged as well. In this specific case, packaging hyphenation 0.6 would require a whole tree of old dependencies, which we try to avoid. I have seen that hyphenation has been updated to 0.7 in textwrap master. Can we expect a release of textwrap any time soon?

**Comment by mgeisler** [comment]
Hi @silwol,

Thanks for the reminder! I'll make a release now!
