### ISSUE TITLE
Hyphenation does weird things to subsequent lines

### ISSUE THREAD

**Issue by alantrick** [mgeisler/textwrap#158]
Consider the code:

```rust
use hyphenation;
use hyphenation::Load;
use textwrap;

let us_hyph = hyphenation::Standard::from_embedded(
    hyphenation::Language::EnglishUS).unwrap();
let input = "participation is the key to sucess";
let wrapper = textwrap::Wrapper::new(10);
let output = "participat\nion is the\nkey to\nsucess";
assert_eq!(output, wrapper.fill(input));
let wrapper = textwrap::Wrapper::with_splitter(10, us_hyph);
let output = "participa-\ntion\n \nis the key\nto sucess";
assert_eq!(output, wrapper.fill(input));
// expected output "participa-\ntion is the\nkey to\nsucess";
````

The first wrapper works okay (though it has to split the word in the middle) but the second wrapper with the hyphenator ends up having a blank third line instead of the expected result (in comments).

This might be a bug in the hyphenator library, but I'm not familiar enough with the code to know.

**Comment by anyakichi** [comment]
I am creating the splitter for Japanese and get the same issue.

This should resolve the issue. https://github.com/anyakichi/textwrap/commit/224f0be75ac6e35b5d82a9d637b060502ec669bb

**Comment by mgeisler** [comment]
Hi @anyakichi, thanks so much for debugging this! I'll be super happy to get your patch in a PR so we can fix this bug.

**Comment by anyakichi** [comment]
I've created a PR!

Thank you for useful library.

**Comment by mgeisler** [comment]
Excellent, thanks very much! I'm travelling for a few days, but I'll try to put out a new release as soon as I can.
