### ISSUE TITLE
Compile-time constant evaluation?

### ISSUE THREAD

**Issue by pickfire** [mgeisler/textwrap#176]
Evaluate at compile-time, zero-cost and no runtime cost at the cost of longer compile time. Of course, lazy-static and similar crates would be an option.

https://github.com/rust-lang/rfcs/blob/master/text/0246-const-vs-static.md

**Comment by mgeisler** [comment]
Hi @pickfire That's an interesting idea — if it's relatively easy to implement with the existing functions?

I always assumed that the cost of wrapping strings would be very low. Also, I expect most programs will spend more time waiting for I/O to complete than waiting for strings to be wrapped.

Do you have a different use case?

**Comment by pickfire** [comment]
@mgeisler Yes, it it supposed to be very low. But then is it useful to have it it runtime when we could do it during compile time? Of course some parts still won't be able to use this feature when it involves `String` or `?Sized`, but no reason we should not do it for `&'static str` which does not change. The best thing I see is, why not do it **just because we can**! :P

**Comment by mgeisler** [comment]
Thanks to @althonos, this is now possible. Please see his `textwrap-macros` crate: https://github.com/althonos/textwrap-macros. It let's you indent, dedent, and wrap strings — all at compile time.

**Comment by pickfire** [comment]
Nice, but should we mention it in README and the first page in rustdoc to make it more discoverable?

**Comment by mgeisler** [comment]
Yeah, mentioning it in the documentation is a great idea!

I don't think `textwrap` should have a dependency on `textwrap-macros` — since `textwrap-macros` already has a dependency back to `textwrap`. It seems simpler to me to have the layering work like this:

    textwrap-macros
        |
        v
    textwrap-macros-impl
        |
        v
    textwrap

Then there is no doubt as to what version is in play at any point.
