### ISSUE TITLE
Add support for finding terminal size and use that for splitting

### ISSUE THREAD

**Issue by mgeisler** [mgeisler/textwrap#19]
We could ship with a convenience function that will automatically find the terminal width on Unix and Windows and wrap the text accordingly.

**Comment by kbknapp** [comment]
Take a look at [term_size](https://crates.io/crates/term_size) if you haven't already :wink: I'd also welcome any contributions to that crate.

**Comment by mgeisler** [comment]
@kbknapp Thanks, I was already thinking of using that!
