### ISSUE TITLE
Non breaking words

### ISSUE THREAD

**Issue by truchi** [mgeisler/textwrap#193]
Hello,

When I run:

```rust
let text = "textwrap: a small library for wrapping text.";

println!(
    "{}",
    textwrap::Wrapper::new(1).break_words(false).fill(text)
);
```

I get the non-expected results:

```
textwrap:
 
a
small
 librar
y
 fo
r
 wrappin
g
 text
.
```

Yet I expect:

```
textwrap:
a
small
library
for
wrapping
text.
```

Same with 2, 3, 4 ...

Thank you!

**Comment by mgeisler** [comment]
Hi @truchi! Oh wow, that looks odd... I'll take a look and try to fix it as soon as possible. Thanks for the report.

**Comment by truchi** [comment]
You are welcome, sir. Thank you for the fix!
