### ISSUE TITLE
Support for columns

### ISSUE THREAD

**Issue by wucke13** [mgeisler/textwrap#205]
Hi, I would love to be able to wrap a text into mutiple columns. 

Something like this quick draft could be the API for it.
```
pub fn columns (s: &str, columns: usize, width: usize, outer_gap: usize, inner_gap: usize );
```

**Comment by mgeisler** [comment]
Hi @wucke13! Oh, that's a cool idea!

I guess the function should return a `String`? A string with the text already formatted into the columns? So if your text above is wrapped into 12 columns, it should return a string looking like this:

```
  Hi, I would   │  Something
  love to be    │  like this
  able to wrap  │  quick draft
  a text into   │  could be the
  mutiple       │  API for it.
  columns.      │
```

**Comment by wucke13** [comment]
Yes! I think the interspace between the columns should be an `&str` Argument. That users can easily decide what type of seperation they desire (just spaces, pipes, UTF-8 magic, you name it). The space before the first column and after the last one maybe should be configurable as well? Other than that, I think only the maximum width and the ammount of columns must be configurable.

So, new API proposal

```Rust
fn columns(
    text: &str,
    columns: usize,
    total_width: usize,
    left_gap: &str,
    middle_gaps: &str,
    right_gap: &str,
);
```

**Comment by mgeisler** [comment]
Hi @wucke13 — I'm sorry, I forgot to reply back to you!

Yes, I think it's pretty clear what you mean and I think your function signature is great! I like the general `&str` arguments for the gaps. I would call it `wrap_columns` to clearly relate it to the existing `wrap` function.

The way I generated the example above was to wrap the text at 12 columns and then simply copy-paste the wrapped lines from the second half after the first half.

So I think it should be possible to implement this by first wrapping the text using the column with given (so `total_width: usize` should actually be [`options: WrapOptions` now, just like `wrap`][1]). Then collect the wrapped lines into a `Vec<Cow<'_, str>>`, count the number of lines finally rearrange the lines. I don't know if your `HashMap<String, String>` code above does something similar?

[1]: https://github.com/mgeisler/textwrap/blob/e49a2a3366ff776877d4454e5637f60b7ff6d6bb/src/lib.rs#L695

Here is a sketch of what I have in mind:

```rust
let wrapped_lines = wrap(text, options).collect::<Vec<_>>();
let lines_per_column = wrapped_lines.len() / columns; // Need to round this up 
let columns = Vec::new();
for line_no in 0..lines_per_column {
    let mut line = String::from(left_gap);
    for column_no in 0..columns {
        line.push_str(lines[line_no + column_no * lines_per_column]);
        if column_no < columns - 1 {
            line.push_str(mid_gap);
        }
    }
    line.push_str(right_gap);
    columns.push(line);
}
```

There are certainly rounding errors in this :smile:  Also, it just occured to me that the lines would need padding, just like you do above with `format!`...

Would you be up for implementing this? It would need some documentation, tests, etc...

**Comment by wucke13** [comment]
Hi, currently I've got a somewhat hefty workload, so I don't want to make any promises. But I just put in on my todo list, let's see whether I will come up with results in the next couple of weeks.

**Comment by mgeisler** [comment]
That's perfectly fine, no promises needed! I'll simply let the issue be open in case you find time :smile:

**Comment by mgeisler** [comment]
I went ahead and wrote a little column wrapping function, see #282.
