### ISSUE TITLE
Support for tabs and hanging indent

### ISSUE THREAD

**Issue by cmcqueen** [mgeisler/textwrap#211]
The use case I'm thinking of is for a command-line program describing its options. Eg

```
-i <filename>   Input file. ELF, PE (portable executable)
                object file formats are accepted.
-o <filename>   Output file. Binary, Intel hex or Motorola
                hex file formats are accepted.
```

**Comment by mgeisler** [comment]
Hi @cmcqueen  That's a great use case! We do have some support for this already via the `initial_indent` and `subsequent_indent` fields on [`Wrapper`](https://docs.rs/textwrap/0.12.1/textwrap/struct.Wrapper.html#method.initial_indent).

That is, you can do this kind of indentation by first constructing the `"-i <filename>   "` part, set that as `initial_indent` and then construct a string with spaces of the same length for the `subsequent_indent`, Something like this:

```rust
pub fn main() {
    let options = vec![
        (
            'i',
            "filename",
            "Input file. ELF, PE (portable executable) object file formats are accepted.",
        ),
        (
            'o',
            "filename",
            "Output file. Binary, Intel hex or Motorola hex file formats are accepted.",
        ),
        (
            'v',
            "int",
            "Verbosity level. Set to 42 to receive more output than you ever wanted.",
        ),
    ];

    for (short, param, help) in &options {
        let left_column = format!("-{} <{}>", short, param);
        // Adjust 20 as needed, perhaps compute it from the longest parameter name
        let initial_indent = format!("{:1$}", left_column, 20); 
        let subsequent_indent = " ".repeat(20);
        let wrapper = textwrap::Wrapper::new(65)  // 65 is your line width
            .initial_indent(&initial_indent)
            .subsequent_indent(&subsequent_indent);
        println!("{}", wrapper.fill(help));
    }
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e9dee5c9400ad9775f8c9e2b5984193f).

If you want to be more careful, you should measure the length of the strings using the [unicode-width crate](http://docs.rs/unicode_width), just like textwrap does internally.

Does this help? By the way, crates like [clap](http://docs.rs/clap) already do this kind of formatting for you.

**Comment by mgeisler** [comment]
Having written the code above, I realize that it could be useful to ship a utility function that does this kind of thing.

**Comment by cmcqueen** [comment]
Thanks, `initial_indent` and `subsequent_indent` are great (as for that Python package).

I guess they're not so easy to find in the documentation, since one doesn't find them on the main page, but has to follow the `Wrapper` struct link to find them. Whereas in the [Python `textwrap` documentation](https://docs.python.org/3/library/textwrap.html), they're described succinctly on the one documentation page.

**Comment by mgeisler** [comment]
Thanks, that's good feedback! I think I need a Features section somewhere on the first page you see in the documentation. Like this:

# Features

* Supports Unicode characters and emojis.
* Support for hanging indentation via the `initial_indent` and `subsequent_indent`.
* Automatic handling of ANSI color codes.
* more stuff as I think of it :-)

I'll keep the issue open so I remember to update the documentation like this before the next release.
