### ISSUE TITLE
Support not squeezing whitespace

### ISSUE THREAD

**Issue by mgeisler** [mgeisler/textwrap#28]
We currently split the input string by whitespace and process the words one by one. This implies that we squeeze runs of whitespace to a single space.

We could instead have a mode where whitespace is significant and kept in the output. This would make it possible to wrap text like this line by line:
```
foobar:    Have lots of foos and bars in the output.
baz:       Show a single bar in the output, but only if it is a full moon.
```
Lines that wrap would still line up somewhat:
```
foobar:    Have lots of foos and bars in
the output.
baz:       Show a single bar in the output,
but only if it is a full moon.
```

In [Python's textwrap][1] this option is called `replace_whitespace`, but I think I'll call it `squeeze_whitespace` instead. The option should come in handy to support the output wanted in https://github.com/kbknapp/clap-rs/issues/617.

[1]: https://docs.python.org/3/library/textwrap.html

**Comment by najamelan** [comment]
Hi,
I needed to wrap text  in rust and thus tried this crate. I quickly ran into limitations, like squeezing the whitespace, breaking on non-break spaces, before punctuation etc... so I set off trying to remedy that, which was a bit more hassle than I anticipated, but currently I have something that does the job and that has quite some margin for improvement, extension, so I thought it might interest you. The code is at: https://github.com/najamelan/unicode-wrap and it is very much draft. I'm a total beginner to rust, and not a unicode expert either. 

I kind of stole your example and benchmarks. I hope that's ok, if not let me know. I can also add attribution if you would like. Haven't done that yet. Having the same benchmarks allows comparing performance and thus, unicode-wrap is 10 times slower than textwrap on my system. 

ps: currently there is no documentation...

greets,
Naja
