### ISSUE TITLE
Allow customising the character that seperates line

### ISSUE THREAD

**Issue by arijit79** [mgeisler/textwrap#362]
The default character that is used for seperation of lines is `\n`, although it would be great there was a function that would allow to change this character to something else 

I would open a PR adding a function that does this, if the author doesn't have any objections

**Comment by mgeisler** [comment]
Hey @arijit79,

Sure, let me know what kind of API you have in mind and we can talk about it.

However, let me try and understand what you're trying to do. Are you thinking of the `\n` inserted when you use `textwrap::fill`, or are you thinking of how we wrap each line individually and find the lines by splitting on `\n`?

If it's the first, then you can use `textwrap::wrap` instead like this ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4eebc79a38e30d5358990c8b23de898b)):

```rust
    let text = "Here are some example words";
    println!("{:?}", textwrap::wrap(text, 10).join("|"));
```

That gives you
```
"Here|are some|example|words"
```

If it's the second, then I think you currently need some more steps. Something like this seems to work ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cd64b3fb3f38b03ffc5d214f676972f2)):

```rust
    let text = "This is the first line.|The second line.";
    println!(
        "{:?}",
        text.split('|')
            .flat_map(|line| textwrap::wrap(line, 10))
            .collect::<Vec<_>>()
            .join("|")
    );
```

This gives you

```
"This is|the first|line.|The second|line."
```

Is that the kind of output you had in mind?

**Comment by arijit79** [comment]
I was talking about the first one. It would have been great to provide a *nicer* API to that, but since you already gave another solution, I am okay with it

**Comment by mgeisler** [comment]
Okay, cool! Since it's possible to solve with a one-liner, I think we don't need to expand the API here.
