### ISSUE TITLE
Option not to split words longer than a line

### ISSUE THREAD

**Issue by veikman** [mgeisler/textwrap#384]
As the documentation states,  “`NoHyphenation` implements `WordSplitter` by not splitting the word at all.” However, `textwrap::wrap` effectively overrides the stated behaviour when the width of a word exceeds the configured maximum width of a line.

For contrast, Python provides a [`break_long_words`](https://docs.python.org/3/library/textwrap.html#textwrap.TextWrapper.break_long_words) option to allow individual words to exceed a given line width without being split. This allows long URLs, for example, to be preserved, which is useful.

As a Rust newbie, I would like to know what it would take to get that freedom in `textwrap`.

**Comment by veikman** [comment]
I now see there is a `break_words` option. Jolly good!

**Comment by mgeisler** [comment]
Hi @veikman, glad you found the `break_words` option! I've actually been wondering if I should rename it to `break_long_words` to make its function a bit clearer and also to keep the connection with Python's API.

**Comment by veikman** [comment]
Clarifying the documentation would be helpful; I don’t think you need to rename the option.

I now understand that although `NoHyphenation` is a `WordSplitter`, it does not split words (a paradox!), and although it does not split words, words are still split if it is chosen (by “breaking” in a separate stage, if `break_words` is `true`, independently of `NoHyphenation`; a separate paradox). The combination of these two paradoxes confused me.

I suggest making an explicit distinction, in the documentation of `NoHyphenation` and `WordSplitter`, between “splitting” (marking advantageous points within a word to _decompose_ it, without breaking the language) and “breaking” (disregarding said points for higher-level reasons; breaking the language), and referring to `break_words`.
