### ISSUE TITLE
crates.io version `0.15.1`

### ISSUE THREAD

**Issue by niyaznigmatullin** [mgeisler/textwrap#484]
Seems that `0.15.1` was removed from crates.io. Can we have a version that will be resolved by cargo when `0.15.1` is specified in `Cargo.toml`?

**Comment by jessebraham** [comment]
Please upload a `0.15.2`, even if it's identical to `0.15.0`. I maintain multiple applications using `clap` which are no longer installable via `cargo install` because this version was yanked.

**Comment by mgeisler** [comment]
A 0.15.2. release has been made in #486 — it's identical to the 0.15.0 release and it is thus a safe semver-compatible target for people trying to install `^0.15.1`.

I'm sorry about the breakage! Lesson learnt: don't yank a crate if you don't offer a semver-compatible upgrade path to downstream users. I had not run into this corner-case before but now I know.
