### ISSUE TITLE
use of undeclared crate or module `hyphenation`

### ISSUE THREAD

**Issue by noble-varghese** [mgeisler/textwrap#505]
When trying to compile the code shown on the example in - https://github.com/mgeisler/textwrap/blob/edc56bfe9556ac84fd1ff7ee23e52352b86bb9d2/examples/hyphenation.rs 
I get the following the error as shown on the screenshot attached here. The error says "use of undeclared crate or module `hyphenation`". How do I resolve this. 
![image](https://user-images.githubusercontent.com/109506617/236752213-e7a6f399-aee2-4760-b519-1b2849fb9b05.png)

**Comment by mgeisler** [comment]
Hi @noble-varghese,

The code there depends on the [hyphenation](https://lib.rs/hyphenation) crate declared in the [`Cargo.toml` file](https://github.com/mgeisler/textwrap/blob/master/Cargo.toml#L32).

**Comment by mgeisler** [comment]
You can actually see this in the [`Cargo.toml` file`](https://github.com/mgeisler/textwrap/blob/master/Cargo.toml#L15-L18) which says

```toml
[[example]]
name = "hyphenation"
path = "examples/hyphenation.rs"
required-features = ["hyphenation"]
```

for this particular example. This means that Cargo will give you an error if you try to run the example without the necessary feature:

```
% cargo run --example hyphenation
error: target `hyphenation` in package `textwrap` requires the features: `hyphenation`
Consider enabling them by passing, e.g., `--features="hyphenation"
```

I hope that helps!
