### ISSUE TITLE
Unit of column width

### ISSUE THREAD

**Issue by sry948749099** [mgeisler/textwrap#516]
Is there a way to wrap lines in pixels instead of bytes?

**Comment by mgeisler** [comment]
Hi @sry948749099,

Yes, see https://mgeisler.github.io/textwrap/ for an example where Textwrap is used to wrap text based on pixels.

The important part is [this implementation of `Fragment`](https://github.com/mgeisler/textwrap/blob/master/examples/wasm/src/lib.rs#L148). The [`Fragment`](https://docs.rs/textwrap/latest/textwrap/core/trait.Fragment.html) trait is what Textwrap uses when wrapping: you should implement it for your own custom type and then you'll be able to use all the wrapping algorithms on this type.

**Comment by sry948749099** [comment]
> Hi @sry948749099,
> 
> Yes, see https://mgeisler.github.io/textwrap/ for an example where Textwrap is used to wrap text based on pixels.
> 
> The important part is [this implementation of `Fragment`](https://github.com/mgeisler/textwrap/blob/master/examples/wasm/src/lib.rs#L148). The [`Fragment`](https://docs.rs/textwrap/latest/textwrap/core/trait.Fragment.html) trait is what Textwrap uses when wrapping: you should implement it for your own custom type and then you'll be able to use all the wrapping algorithms on this type.

Get it! Thanks for your quickly respose!
