### ISSUE TITLE
What is the `width` in `Options`?

### ISSUE THREAD

**Issue by kkew3** [mgeisler/textwrap#546]
The [doc](https://docs.rs/textwrap/latest/textwrap/struct.Options.html#structfield.width) says it's the number of columns. But this code compare it against `str::len`, which is a measure in terms of bytes, not the display width:

https://github.com/mgeisler/textwrap/blob/63970361d1d653ec8715acb931c3c109750d4a57/src/wrap.rs#L205

which confuses me a lot. Shouldn't it be something like:

```rust
if display_width(line) < options.width && indent.is_empty() { ... }
```

Thanks!

**Comment by mgeisler** [comment]
Hi @kkew3, thanks for asking! This is something I should have documented with a comment.

The change was done in #478 and the idea is to be conservative: in the worst case, each _byte_ of the string contributes with one column width. That is, printable ASCII text is the widest terminal text per byte of input.

Characters like `'ø'`, `'é'`, and `'α'` have a display width of only one column, but are encoded in multiple bytes. So we might end up on the slow path if the input has many such characters.

CJK characters take up two columns when using the `unicode-width` feature. However, they take up more than two bytes in their UTF-8 encoding: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9358e3b128a3b5b603c8206b62baffdd).

Please let me know if you find flaws in this assumption!

**Comment by kkew3** [comment]
Thanks for the explanation!

**Comment by mgeisler** [comment]
No problem! I would be happy to add a comment about this to the source so that other's won't have to wonder the same in the future.
