### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by RazrFalcon** [mgeisler/textwrap#61]
1. You should add a new line [here](https://github.com/mgeisler/textwrap/blob/master/src/lib.rs#L17). Currently it rendered as one line: https://docs.rs/textwrap/0.6.0/textwrap/index.html
2. Also a new line is missed [here](https://github.com/mgeisler/textwrap/blob/master/src/lib.rs#L91), but struct doesn't support examples, probably, so in doc it looks like this: `Use this as a Wrapper.splitter to avoid any kind of hyphenation: ``` use textwrap::{Wrapper, NoHyphenation};`

**Comment by mgeisler** [comment]
Oh, thank you very much for telling me! Sorry for not reacting on this sooner, for some reason, it seems I'm not automatically subscribed to all issues in my own repository.
